### ISSUE TITLE
test case Omega

### ISSUE THREAD

**Issue by thareUSGS** [epn-vespa/fits2vrt#2]
From the psup site, a good test case for the script would be the Omega mosaic: albedo_r1080_equ_map.fits
http://psup.ias.u-psud.fr/sitools/client-user/index.html?project=PLISonMars
currently fails conversion.

**Comment by cmarmo** [comment]
Hi Trent,
I converted the albedo map from ISIS cub format to FITS for publication via PSUP. At that time I had'nt yet defined all keywords useful for GIS. Necessary keywords are missing in albedo_r1080_equ_map.fits. In addition to that, CAR projection was not supported by fits2vrt until now.
I think I have fixed both issues now in commit  ad3881a81da9dfd1dcdc0b087646755e9b047229
- When non mandatory keywords are missing fits2vrt throws a warning but does not exit
- CAR projection is supported

Updating metadata in PSUP would be the best solution, but I'm not working on it anymore.
